const FETCH_POSTS = 'FETCH_POSTS';

const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';

const FETCH_USER_INFO = 'FETCH_USER_INFO';

export {FETCH_POSTS, USER_LOGIN, USER_LOGOUT, FETCH_USER_INFO};
