const FETCH_REDDIT_POSTS = 'FETCH_REDDIT_POSTS';

const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';

const FETCH_POSTS = 'FETCH_POSTS';

const FETCH_USER_INFO = 'FETCH_USER_INFO';

export {
  FETCH_REDDIT_POSTS,
  USER_LOGIN,
  USER_LOGOUT,
  FETCH_POSTS,
  FETCH_USER_INFO,
};
