const images = {
  redditLogo: require('./redditLogo.png'),
  googleLogo: require('./googleLogo.png'),
  closeIcon: require('./close.png'),
  redditLogoWithText: require('./redditLogowithText.png'),
  home: require('./home.png'),
  home_selected: require('./home_selected.png'),
  comunities: require('./comunities.png'),
  comunities_selected: require('./comunities_selected.png'),
  addPost_selected: require('./addPost_selected.png'),
  chat: require('./chat.png'),
  chat_selected: require('./chat_selected.png'),
  inbox: require('./inbox.png'),
  inbox_selected: require('./inbox_selected.png'),
  searchIcon: require('./searchIcon.png'),
  coinIcon: require('./coinIcon.png'),
  circle: require('./circle.png'),
  upvote: require('./arrow-up.png'),
  downvote: require('./arrow-down.png'),
  comment: require('./comment.png'),
  share: require('./share.png'),
  giftIcon: require('./giftIcon.png'),
  compassIcon: require('./compass.jpg'),
  profile: require('./profile.png'),
  profileSelected: require('./profileSelected.png'),
  loginPageRedditIcon: require('./loginRedditIcon.png'),
};

export default images;
